---
title: "EDS 221: Day 4 Activity"
author: "Takeen Shamloo"
format: html
editor_options: 
  chunk_output_type: console
---

# Day 4 Activity ----

## Task 1 ----

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

my_matrix <- matrix(, nrow = length(weekdays), ncol = length(transects))
for (i in 1:length(weekdays)){
  for (j in 1:length(transects)){
    my_matrix[i, j] <- paste0(weekdays[i], " - ", transects[j])
  }
}
```

## Task 2 ----

```{r}
force <- function(mass, accel){
  print(paste0("The resulting force is ", (mass/accel), " Newtons"))
}

force(mass = 4, accel = 2)
```

## Task 3 ----

```{r}
library(dplyr)
fish_parms <- data.frame(sci_name = c("Chanos chanos",
                                      "Sphyraena barracuda",
                                      "Caranx ignobilis"),
                         common_name = c("Milkfish",
                                         "Great barracuda",
                                         "Giant trevally"),
                         a_est = c(0.0905,
                                   0.0181,
                                   0.0353),
                         b_est = c(2.52,
                                   3.27,
                                   3.05))

fish_weight <- function(name, tot_length){
  my_sub <- fish_parms |> filter(common_name == name)
  print(paste(name, "has a expected fish weight of", (my_sub$a_est * tot_length ^ (my_sub$b_est))))
}

milkfish_weights <- fish_weight(name = "Milkfish", 0:100)
```

## Task 4 ----

```{r}
wave_power <- function(height, period){
  print(paste("Wave power is", (0.5 * height^(2) * period)))
}

wave_power(height = seq(0,3,0.2), period = 8)
```

## Task 5

```{r}
wave_power_with_depth <- function(height, period, depth){
  if (!is.numeric(height)){
    stop("Height is not numeric...")
  }
  
  if (!is.numeric(period)){
    stop("Period is not numeric...")
  }
  
  if (!is.numeric(depth)){
    stop("Depth is not numeric...")
  }
  
  if (depth > 12){
    print(paste("Wave power is", (0.5 * height^(2) * period)))
    message("Deep water equation was used 0.5 * H^2 * T")
  } else {
    print(paste("Wave power is", (0.81 * height^(2) * period)))
    message("Shallow water equation was used 0.81 * H^2 * T")
  } 
}

wave_power_with_depth(height = 12, period = 8, depth = 13)
```




